#!/bin/sh

#title           :80-wrapper
#description     :encapsulate calls of some original Ubuntu MOTD scripts
#author          :zdenek polach ( https://github.com/polachz )
#date            :24.01.2017
#version         :0.1
#usage           :called as part of Message of the day generator
#notes           :
#==============================================================================
#
# MIT License
#
# Copyright (c) 2017 Zdenek Polach

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#==============================================================================

indent()
{
   if [ ! -z "$1" ]; then 
      printf '%s\n' "$1" | while IFS= read -r line
      do
        printf '\t%s\n' "$line"
      done 
   fi
}
if [ -f ./90-updates-available ]; then 
   MYWRP_UPDATES=`. ./90-updates-available`
   indent "$MYWRP_UPDATES"
fi
if [ -f ./91-release-upgrade ]; then
   MYWRP_UPDATES=`. ./91-release-upgrade`
   indent "$MYWRP_UPDATES"
fi
if [ -f ./97-overlayroot ]; then
   MYWRP_UPDATES=`. ./97-overlayroot`
   indent "$MYWRP_UPDATES"
fi
if [ -f ./98-fsck-at-reboot ]; then
   MYWRP_UPDATES=`. ./98-fsck-at-reboot`
   indent "$MYWRP_UPDATES"
fi
if [ -f ./98-reboot-required ]; then
   MYWRP_UPDATES=`. ./98-reboot-required`
   indent "$MYWRP_UPDATES"
fi
unset MYWRP_UPDATES
if [ -f ./warn-msg ]; then
   . ./warn-msg
fi

