#!/bin/sh

#title           :warn-msg
#description     :dumps warning about unauthorized access to MOTD
#author          :zdenek polach ( https://github.com/polachz )
#date            :24.01.2017
#version         :0.1
#usage           :called as part of Message of the day generator by wrapper
#notes           :
#==============================================================================
#
# MIT License
#
# Copyright (c) 2017 Zdenek Polach

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#==============================================================================

COLUMNS=$(tput cols)
CENTER_SIZE=62

S1="!!!!! WARNING !!!!!"
S2="All connections are monitored and recorded"
S3="EXIT IMMEDIATELY if you are not an authorized user!"
printf "\t%${CENTER_SIZE}s\n" | tr ' ' -
#printf "\n"
printf "\t%*s\n" $(((${#S1}+$CENTER_SIZE)/2)) "$S1"
printf "\t%*s\n" $(((${#S2}+$CENTER_SIZE)/2)) "$S2"
printf "\t%*s\n" $(((${#S3}+$CENTER_SIZE)/2)) "$S3"
#printf "\n"
printf "\t%${CENTER_SIZE}s\n" | tr ' ' -
echo

